apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DATABASE_URL: "postgresql://user:password@postgres:5432/habits"
  SECRET_KEY: "k8s-dev-secret-change-me"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  S3_BUCKET: "habit-photos"
